// ============================================================================
// TANISAN SEVERSİN - SORU HAVUZU (QUESTIONS DATABASE)
// 7 Kategori x 150+ Soru = Toplam 1050+ Özenle Hazırlanmış Soru
// ============================================================================

const CATEGORIES = {
  icebreaker: {
    id: 'icebreaker',
    name: 'Yeni Tanışma',
    icon: '🧊',
    tag: 'Buz Kırıcı',
    description: 'Hafif, eğlenceli ve keyifli tanışma soruları',
    theme: {
      primary: '#06b6d4',
      primaryDark: '#0891b2',
      glow: 'rgba(6, 182, 212, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #0e3a47 0%, #061820 100%)',
      cardBg: 'rgba(12, 38, 48, 0.85)',
      badgeBg: 'rgba(6, 182, 212, 0.15)',
      badgeBorder: 'rgba(6, 182, 212, 0.4)',
      textColor: '#e0f2fe'
    },
    questions: [
      "Hayatın boyunca yalnızca tek bir ülkeye seyahat etme hakkın olsaydı, nereyi seçerdin ve neden?",
      "Bugüne kadar tattığın en tuhaf ya da beklenmedik lezzet neydi?",
      "Sana sınırsız bütçeyle bir hobi edinme şansı verilseydi yarın neye başlardın?",
      "Günün en sevdiğin saati hangisi ve o saatte genelde ne yaparsın?",
      "Kendini tek bir film ya da dizi karakteriyle anlatman gerekseydi bu kim olurdu?",
      "Hiç beklemediğin bir anda hayatını kolaylaştıran en ilginç alışkanlığın ne?",
      "Bir müzik aletini bir gecede virtüöz derecesinde çalabilecek olsan hangisini seçerdin?",
      "Çocukken 'Büyüyünce kesin bunu yapacağım' deyip şu an hiç yapmadığın şey ne?",
      "Evinde çıkan yangında tüm canlılar güvendeyse kurtaracağın ilk 3 eşya ne olurdu?",
      "Zaman yolculuğu mümkün olsaydı; geçmişe gidip bir olaya tanıklık mı ederdin, geleceğe mi bakardın?",
      "Sabah uyandığında günün harika geçeceğini hissettiren en küçük detay nedir?",
      "İnsanların senin hakkında ilk bakışta yanıldığı en yaygın ön yargı nedir?",
      "Eğer bir kitap ya da podcast yazacak/yapacak olsan konusu ne olurdu?",
      "Sonsuza kadar sadece 3 çeşit yemek yiyebilecek olsan menün ne olurdu?",
      "Şu ana kadar katıldığın en unutulmaz konser ya da canlı etkinlik hangisiydi?",
      "Sence insanların mutlaka ölmeden önce deneyimlemesi gereken tek bir şey nedir?",
      "Hangi süper gücü seçerdin: Zihin okumak mı, görünmez olmak mı, ışınlanmak mı?",
      "Telefonundaki en çok kullandığın ama pek bilinmeyen uygulama hangisi?",
      "Hafta sonu için ideal kaçamağın: Issız bir dağ kulübesi mi, hareketli bir metropol mü?",
      "İzlemekten asla bıkmadığın, ezbere bildiğin o 'konfor filmi' hangisi?",
      "Bir yabancıyla konuşurken seni en çok etkileyen iletişim tarzı nasıldır?",
      "Şimdiye kadar aldığın en garip ya da en tatlı iltifat neydi?",
      "Kendi hayatının filmi çekilse soundtrack'inde mutlaka çalması gereken şarkı hangisi?",
      "Sosyal medyada karşına çıktığında izlemeden geçemediğin niş bir içerik türü var mı?",
      "Günün yorgunluğunu atmak için yaptığın vazgeçilmez mini ritüelin nedir?",
      "Eğer bir dili anında ana dilin gibi konuşabilecek olsaydın hangi dili seçerdin?",
      "Hiç kimsenin beğenmediği ama senin gizli gizli çok sevdiğin bir şarkı ya da film var mı?",
      "Bir adaya düşsen yanına alacağın tek bir kutu oyunu veya oyun ne olurdu?",
      "Şehir hayatının en çok sevdiğin ve en çok nefret ettiğin yanı nedir?",
      "Bugüne kadar aldığın en iyi hediye neydi ve kimden gelmişti?",
      "Yemek yapmayı bir sanat olarak mı görürsün, yoksa sadece karın doyurmak mı?",
      "Bir günlüğüne dünyaca ünlü birinin yerine geçebilseydin kimin gününü yaşamak isterdin?",
      "Kendi kendine kaldığında en çok ne düşünür veya hayal kurarsın?",
      "Hayatındaki en büyük şans ya da dönüm noktası olarak gördüğün tesadüf neydi?",
      "Koleksiyonunu yaptığın ya da biriktirmeye heves ettiğin bir şey var mı?",
      "Çocukluğunun geçtiği mahalle veya ev dendiğinde burnuna gelen ilk koku nedir?",
      "İlk maaşınla ya da kendi kazandığın ilk parayla ne satın almıştın?",
      "Hangi konuda saatlerce sıkılmadan bir konferans veya sunum yapabilirsin?",
      "En garip fobin ya da mantıksız bulduğun ama korktuğun şey nedir?",
      "Gittiğin bir mekanda atmosferi senin için mükemmel kılan şey nedir: Işık, müzik, koku?",
      "Herkesin çok övdüğü ama senin bir türlü sevemediğin popüler bir şey söyle.",
      "Hayatında aldığın ve 'iyi ki dinlemişim' dediğin en değerli tavsiye neydi?",
      "Bir sabah uyandığında hayvanlarla konuşabilseydin ilk hangi hayvanla sohbet ederdin?",
      "Kendini en yaratıcı ve üretken hissettiğin ortam nasıl bir yerdir?",
      "Şu an hayatında yeni bir sayfa açıyor olsan değiştireceğin ilk şey ne olurdu?",
      "Yolculuk yaparken en çok ne yapmaktan keyif alırsın: Müzik dinlemek, kitap okumak, manzarayı izlemek?",
      "Seni hiç tanımayan birine kendini tek bir cümleyle özetlemen gerekse ne derdin?",
      "Şu an cebindeki parayla hemen yarın kalkıp gidebileceğin bir bilet alsan nereye gidersin?",
      "En çok hangi tarihi dönemin modasını ve yaşam tarzını merak ediyorsun?",
      "Kendinde en çok beğendiğin ve geliştirmekten gurur duyduğun kişisel özelliğin ne?",
      "Gece kuşu musun yoksa sabah erken kalkanlardan mısın? Bu enerjini nasıl etkiliyor?",
      "Son zamanlarda duyduğun ve aklından çıkmayan en ilginç bilgi neydi?",
      "Bir restoranda sipariş verirken garantici misin yoksa her zaman maceracı mısın?",
      "Evcil bir hayvan besledin mi ya da beslemek istediğin sıra dışı bir canlı var mı?",
      "Arkadaşların seni bir kelimeyle tanımlayacak olsa bu kelime ne olurdu?",
      "Gelecekte teknolojinin çözeceğine en çok inandığın insanlık problemi nedir?",
      "Yağmurlu bir pazar gününü geçirmek için senin için en kusursuz senaryo nedir?",
      "Bir kafede otururken etraftaki insanları gözlemleyip hikayeler uydurur musun?",
      "Hayatında bir kez olsun yapıp 'bir daha asla' dediğin çılgınlık nedir?",
      "Gülme krizine girdiğin ve durduramadığın son anı hatırlıyor musun?",
      "Bir tablo ya da sanat eseri satın alacak olsan nasıl bir tarz seçerdin?",
      "Sence ilk tanışmada insanların en çok dikkat ettiği şey samimiyet mi, zeka mı, nezaket mi?",
      "Çocukken inandığın en komik ya da saçma batıl inanç neydi?",
      "Eğer bir bayram veya festival icat etme hakkın olsaydı neyi kutlardık?",
      "Şu anki yaşına gelene kadar öğrendiğin en net hayat dersi nedir?",
      "Sabah kahveni/çayını yaparken aklına gelen ilk şey ne olur?",
      "Tanımadığın birini hayatına almadan önce içgüdüsel olarak neye bakarsın?",
      "Şu an dinlediğin müziğin şarkısını ya da albümünü söyle; bu seçim seni ne anlatır?",
      "Hayatında 'ikinci şansa' inanan biri misin?",
      "Bir kafeye girince oturma yeri seçerken nelere dikkat edersin?",
      "Çevrendeki insanların gözlemlediğin ve 'bunu neden yapıyorlar?' dediğin bir alışkanlık var mı?",
      "Kendi geçmişine baktığında 'o dönem beni şekillendirdi' dediğin tek bir yıl hangisi?",
      "En son ne zaman tamamen yabancı bir şeyi deneyip çok beğendiğin oldu?",
      "Bir şehirde sadece 24 saatin olsa ve o şehri hiç bilmesen ilk yapacağın şey ne?",
      "Seni bir kelimeyle tanımlayan ama sana göre eksik kalan o kelime nedir?",
      "Tatilde deniz mi dağ mı orman mı şehir mi — hangisinde kendinsen?",
      "Yaşlandıkça daha iyi hale geldiğini düşündüğün kişisel özelliğin ne?",
      "Sosyal medyası olmayan biri olsan hayatın nasıl değişirdi?",
      "En son ağlatan film, müzik veya kitap hangisiydi?",
      "Bugün sabah kahvaltında ne yedin? Bu tercih seni ne anlatır?",
      "Komşularınla ilişkin nasıl: Selam verip geçen mi, yoksa sohbet eden mi?",
      "Bir şeyi öğrenmek için kitap, video, deneyerek öğrenme — hangisi sana göre?",
      "Tatil sonrası eve dönerken içinde olan hissin adı ne?",
      "Telefona bakmadan tam bir gün geçirebilir misin?",
      "İnsanlarla ilk tanışırken ismini söyledikten sonra genellikle ne söylersin?",
      "Sinemada en çok hangi tür film seni salona bağlar?",
      "Kendini bir hayvanla özdeşleştirsen hangisi olurdun ve neden?",
      "Restoranda menüye bakmadan sipariş verir misin?",
      "Dünya nüfusu kadar para kazansan ilk harcaman ne olurdu?",
      "Şu an yanında taşıdığın ve vazgeçemediğin tek bir nesne nedir?",
      "Bir şehirde yaşamak zorunda olsan ama kendi şehrinden başka biri — nerede yaşardın?",
      "Gençliğine dönüp bir tavsiye verseydin ne derdin?",
      "Sabahları yüzüne sıçrayan suyun sıcaklığı mı soğukluğu mu?",
      "Şu an hayatında en çok vaktini neye harcıyorsun ve bu seni mutlu ediyor mu?",
      "Evinde misafir ağırlamayı mı seversin, yoksa dışarıda buluşmayı mı?",
      "Bir şeyi anlatırken kelimeler mi yetmez, yoksa sussun sessiz mi oturursun?",
      "Şu an elinde olmayan ama çok istediğin bir deneyim nedir?",
      "Seni tanıyan biri 'bu kesinlikle sen' diyerek paylaştığı son şey neydi?",
      "Çevrendeki insanların en çok sana sorduğu konu hangisi?",
      "Şimdiye kadar gördüğün en güzel gün batımı veya şafak neredeydi?",
      "Hayatında kendini en çok 'doğru yerdeyim' hissettiren an hangisiydi?",
      "Bir ülkeye emekli olmak için gidecek olsan nereyi seçerdin?",
      "Son bir haftada seni en çok güldüren an neydi?",
      "Kendi doğum günün için ideal kutlama nedir: Sürpriz mi, planlı mı, yalnız mı?",
      "Şu an tüm borçların silinse ve bir yıl boyunca istediğini yapabilsen ne yapardın?",
      "Bir şeyden vazgeçmekte zorlandığında kendini ne ile ikna edersin?",
      "Kişisel gelişim konusunda en etkili bulduğun yöntem nedir?",
      "Bir toplantıda ya da sohbette en çok kimin sözünü dinlersin?",
      "Hayatında hiç gerçekten yanlış zamanda yanlış yerde olduğunu hissettin mi?",
      "Şu an seni en çok heyecanlandıran ve beklediğin olay nedir?",
      "Birine güvenmekte ne kadar süren biri misin?",
      "Konfor alanından çıkmak için içinde ne kadar güçlü bir itmeye ihtiyaç duyarsın?",
      "Şu an dünyanın neresinde olmak isterdin?",
      "Gece uyumadan önce aklından geçen son düşünce genellikle ne olur?",
      "Şu an hayatına dahil etmek istediğin yeni bir alışkanlık nedir?",
      "Bugüne kadar aldığın en sürpriz karar ne oldu?",
      "Bir konuda hiç hata yapmadan ustalaşabilseydin bu ne olurdu?",
      "Kendine baktığında gördüğün ve diğerlerinin görmediği tarafın nedir?",
      "Şu an sessize alman gereken bir iç sesin olsa o ses ne söylüyor olurdu?",
      "Bu odada seninle tanışmış olmaktan en çok ne umut edersin?"
    ]
  },

  friends: {
    id: 'friends',
    name: 'Arkadaşlar Arası',
    icon: '👬',
    tag: 'Samimi & Dostluk',
    description: 'Arkadaş grubunu daha derin tanıyıp bağları güçlendirecek sorular',
    theme: {
      primary: '#f59e0b',
      primaryDark: '#d97706',
      glow: 'rgba(245, 158, 11, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #451a03 0%, #1c0a00 100%)',
      cardBg: 'rgba(56, 25, 6, 0.85)',
      badgeBg: 'rgba(245, 158, 11, 0.15)',
      badgeBorder: 'rgba(245, 158, 11, 0.4)',
      textColor: '#fef3c7'
    },
    questions: [
      "Bu gruptaki insanlarla birlikteyken kendini en çok 'kendi gibi' hissettiğin an hangisiydi?",
      "Benimle ya da bu gruptan biriyle yaşadığın ve asla unutamadığın en absürt anı nedir?",
      "Eğer bir gün başın büyük bir belaya girse gruptan ilk kimi ararsın ve neden?",
      "Bizim hakkımızda dışarıdan birine bahsederken en çok hangi özelliğimizle övünürsün?",
      "Arkadaşlığımız boyunca bana söylemek isteyip de doğru zamanı bulamadığın bir şey var mı?",
      "Grupta bir zombi istilası çıksa ilk kim hayatta kalır, ilk kim feda edilir?",
      "Benim en tahammül etmekte zorlandığın ya da 'yine başladı' dediğin huyum ne?",
      "Birlikte çıktığımız yolculuklar ya da planlar arasında senin için 1 numara hangisiydi?",
      "Gruptaki herkesin bir ortak özelliği olsaydı bu ne olurdu?",
      "Eğer bu gruptan biriyle bir şirket kuracak olsan kimi ortak seçerdin ve ne satardınız?",
      "Benim hayatımda yaptığım en kötü veya en komik seçim sence neydi?",
      "Zor bir dönemden geçerken bu gruptan aldığın en iyi destek neydi?",
      "Grupta en çok kimin aşk hayatı kaotik ve kimin tavsiyelerine asla güvenilmez?",
      "Aramızdaki bağın zayıflamasından hiç korktuğun bir dönem oldu mu?",
      "Bana dışarıdan bakan birinin asla tahmin edemeyeceği bir özelliğimi söyler misin?",
      "Eğer bir gün birimiz zengin olursa gruptan ilk kime ne almalı?",
      "Benim hakkımda ilk tanıştığımızda düşündüğün ama sonradan değişen fikrin neydi?",
      "Birlikte sabaha kadar oturup konuştuğumuz ve sana çok iyi gelen o geceyi hatırlıyor musun?",
      "Grupta en çok kimin sır tutma becerisine güvenirsin?",
      "Eğer benim yerimde bir günlüğüne yaşasaydın hayatımda ilk neyi değiştirirdin?",
      "Beni bir dizi/film karakteriyle eşleştirsen bu kim olurdu?",
      "Aramızdaki en komik veya en saçma kavga/tartışma ne yüzünden çıkmıştı?",
      "Birbirimize verdiğimiz ama unuttuğumuz bir söz var mı?",
      "Gruptaki herkes hakkında tek bir olumlu kelime söylemen gerekirse kim için ne dersin?",
      "Sence aramızda yaşlanınca en huysuz dede/nine kim olacak?",
      "Senin moralin çok bozukken seni en hızlı güldüren gruptan kimdir?",
      "Hiç gruptan birini kıskandığın veya 'keşke ben de onun gibi olsam' dediğin bir an oldu mu?",
      "Bizim arkadaşlık dinamiğimizi anlatan tek bir şarkı seçsen hangisi olurdu?",
      "Bana sormak isteyip de kırılacağımdan korktuğun bir soru var mıydı?",
      "Grupta en çok kime borç para verirken hiç düşünmezsin?",
      "Eğer bir gün hepimiz farklı şehirlere/ülkelere dağılsak bağımızı ne korur?",
      "Benim en çok hangi başarımı kutladığında gerçekten içten gurur duydun?",
      "Gruptaki en iyi dert dinleyen kişi sence kim?",
      "Birlikte yaptığımız en rezil ama şu an gülerek anlattığımız olay neydi?",
      "Benim flört veya ilişki seçimlerim hakkında dürüst bir eleştiri yapsan ne derdin?",
      "Gruptan kiminle 1 ay boyunca ıssız bir adada baş başa kalmaya katlanabilirsin?",
      "Bana verdiğin ve sonradan 'keşke öyle demeseydim' dediğin bir tavsiye var mı?",
      "Sence bu grupta duygularını en çok içine atan ve saklayan kim?",
      "Senin gözünde bu arkadaş grubunun en vazgeçilmez kuralı veya yazılı olmayan yasası nedir?",
      "Benim hangi yeteneğimin veya potansiyelimin yeterince farkında olmadığımı düşünüyorsun?",
      "Birlikte yediğimiz en efsane yemek ya da gittiğimiz en güzel mekan hangisiydi?",
      "Gruptan birinin düğününde en çok ağlayacak ve en çok dans edecek kişi kim olur?",
      "Benimle ilgili öğrendiğinde en çok şaşırdığın gerçek neydi?",
      "Birlikte bir suç işleyecek olsak (örneğin müze soygunu) plandaki rollerimiz ne olurdu?",
      "Arkadaşlığımızda seni en çok mutlu eden küçük bir jest ya da an söyler misin?",
      "Gruptaki kişilerden birer özellik çalma hakkın olsa kimden neyi alırdın?",
      "Bana söylemek istediğin ama ertelediğin bir teşekkür var mı?",
      "Sence biz 10 yıl sonra nerede, nasıl bir hayat yaşıyor olacağız?",
      "Aramızdaki en 'mantık insanı' ve en 'duygu insanı' kim?",
      "Benim hayatımdaki en büyük dönüm noktasına şahit olduğun an hangisiydi?",
      "Grup içinde dedikodu yaparken en çok kimin adına endişeleniyoruz?",
      "Birbirimize taktığımız en komik lakap ya da aramızdaki en komik içeriden şaka nedir?",
      "Senin için 'gerçek dost' tanımını bu grupta en çok karşılayan davranış ne oldu?",
      "Benimle yalnız vakit geçirmek ile kalabalık bir ortamda olmak arasındaki fark nedir?",
      "Sence bu grupta en çabuk gaza gelen ve çılgınca fikirler ortaya atan kim?",
      "Bir gün anılarımızı anlatan bir kitap yazılsa başlığı ne olurdu?",
      "Beni en çok neyin üzdüğünü ya da öfkelendirdiğini biliyor musun?",
      "Gruptan kimin anne/babasıyla aran daha iyi?",
      "Birbirimizi en son ne zaman sıkıca kucakladık ve o an ne hissettin?",
      "Bana karşı hiç haksızlık yaptığını düşünüp sonradan pişman olduğun bir an var mı?",
      "Sence grupta tarzını veya giyimini en çok beğendiğin kişi kim?",
      "Benimle ilgili değiştirmemi ASLA istemeyeceğin en karakteristik huyum nedir?",
      "Grupça yaptığımız ve gelenekselleşmesini istediğin bir aktivite var mı?",
      "Birbirimizin hayatında olmasaydık sence şu an nasıl insanlar olurduk?",
      "Şu an bu masada olan herkese içinden gelen en samimi cümleyi kurar mısın?",
      "Benim hakkımda sosyal medyada paylaşmak isteyip de paylaşmadığın bir şey var mı?",
      "Bu gruptaki en büyük sırrı bilen sen misin yoksa başkası mı?",
      "Birlikte en uzun süre hiç konuşmadan oturduğumuz ve ne hissettiğin anı hatırlıyor musun?",
      "Benim için yapabileceğin en büyük fedakarlık nedir?",
      "Grupta kimin kariyer seçimi seni en çok şaşırtmıştı?",
      "Bu arkadaşlık içinde en çok ne zaman 'şanslıyım' diyorsun?",
      "Birimizle ilgili aklında taşıdığın bir soru var mı, şimdi sorabilirsin?",
      "Gruptan birinin evine taşınmak zorunda kalsan kiminle en uzun süre geçinebilirdin?",
      "Bana sorulmadan yaptığın en güzel iyilik hangisiydi?",
      "Sence bu grubun ortak zayıflığı ne?",
      "Birlikte plan yapıp en çok hangi seferinde planı iptal ettik?",
      "Şu an bana söylediğinde kalbimi en çok ısıtacak cümle ne olurdu?",
      "Bu grupta en çok kimi anlayamadığını ama sevmeye devam ettiğini itiraf et.",
      "Birlikte yaptığımız ve sence değeri bilinmeyen küçük geleneklerimiz neler?",
      "Benden beklediğin ama bir türlü söylemediğin bir şey var mı?",
      "Gruptan kiminle en uzun süre küs kaldın ve o sürece nasıl baktın?",
      "Şu an bu grubun enerjisini bir kelimeyle tanımlamak zorunda kalsan ne derdin?",
      "Beni diğer arkadaşlarından ayıran en belirgin fark sence nedir?",
      "Grupça kriz anında en çok kimin sakin kaldığını gözlemledin?",
      "Birlikte kahkaha attığımız ve şu an bile düşününce güldüğün o an nedir?",
      "Sence bu grup olmasaydı sen bugün kim olurdun?",
      "Bana bakıp 'bu kişi büyük işler yapacak' dediğin bir an oldu mu?",
      "Grupta kimin en fazla değiştiğini düşünüyorsun ve bu değişim iyi mi kötü mü?",
      "Birlikte bir maceraya atılacak olsak nasıl bir ekip oluştururuz?",
      "Bu arkadaşlıkta seni en çok büyüten deneyim hangisiydi?",
      "Benim hakkımda içinde sakladığın nazik bir gözlemin var mı?",
      "Grupta kimin varlığını en çok 'hafifletiyor' ve rahatlatıyor?",
      "Birlikte geçirdiğimiz zamanın sonu geldiğinde genellikle ne hissedersin?",
      "Bu masadaki kişilere gerçekten şükran duyan biri misin?",
      "Şu an gözlerimi kapatsan ve sadece seslerden herkesi tanısan ilk kimi ayırt ederdin?",
      "Birlikte bir ev kiralayıp yaşasaydık evin hangi bölümünü hemen sahiplenirdin?",
      "Bu gruptaki herkese aynı soruyu soran biri sana hangi soruyu sorardı?",
      "Şu an sadece bana söyleyebileceğin, gruba değil, bir şey var mı?"
    ]
  },

  flirt: {
    id: 'flirt',
    name: 'Flört & İlk Buluşma',
    icon: '💘',
    tag: 'Romantik & Çekim',
    description: 'İki insan arasındaki kıvılcımı tutuşturan, romantik ve merak uyandırıcı sorular',
    theme: {
      primary: '#ec4899',
      primaryDark: '#db2777',
      glow: 'rgba(236, 72, 153, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #500724 0%, #1f020d 100%)',
      cardBg: 'rgba(64, 8, 30, 0.85)',
      badgeBg: 'rgba(236, 72, 153, 0.15)',
      badgeBorder: 'rgba(236, 72, 153, 0.4)',
      textColor: '#fce7f3'
    },
    questions: [
      "Beni ilk gördüğün ya da ilk konuştuğumuz an aklından geçen ilk düşünce neydi?",
      "Bir insanda seni ilk 5 dakikada en çok etkileyen şey nedir: Ses tonu, bakışlar, espri anlayışı?",
      "Senin için 'mükemmel bir ilk randevu' senaryosu nasıl başlar ve nasıl biter?",
      "Aşkta kadere ve tesadüflere inanır mısın, yoksa her şey seçimlerden mi ibarettir?",
      "Bir ilişkide olmazsa olmaz dediğin, asla taviz veremeyeceğin 3 değer nedir?",
      "Karşındaki insanın senden hoşlandığını en net nasıl anlarsın?",
      "Flört ederken cesur ve açık sözlü müsün yoksa ağırdan alıp karşı tarafı mı beklersin?",
      "Bende dikkatini çeken en çekici ya da sempatik detay nedir?",
      "Sence bir ilişkide tutku mu daha önemlidir yoksa huzur ve güven mi?",
      "Aşkını gösterme dilin hangisidir: Sözler, hediyeler, fiziksel temas, kaliteli zaman, yardım etmek?",
      "Hiç birine ilk görüşte aşık oldun mu yoksa tanıdıkça mı seversin?",
      "Senin kalbini çalmanın en kestirme ve garantili yolu nedir?",
      "Bir ilişkide en çok korktuğun şey nedir: Bağlanmak, terk edilmek, monotonlaşmak?",
      "Şu ana kadar yaptığın ya da sana yapılan en romantik jest neydi?",
      "Göz teması kurduğumuzda ne hissediyorsun: Heyecan, merak, huzur?",
      "Bir erkekte/kadında 'red flag' olarak gördüğün ilk davranış nedir?",
      "Sence bir çiftin birlikte yapabileceği en eğlenceli ve bağ kurucu aktivite nedir?",
      "Geçmiş ilişkilerinden öğrendiğin en büyük ilişki dersi ne oldu?",
      "Sabah sevgilinin yanında uyanıp ilk ne yapmak istersin?",
      "Karşındaki kişinin zekası ve mizah yeteneği senin için ne kadar çekici?",
      "Birlikte yağmurlu bir gecede baş başa kalsak ne yapmak isterdin?",
      "Eski sevgililerinle arkadaş kalabilenlerden misin, yoksa tamamen silenlerden mi?",
      "Beni tanımak için bana sorabileceğin tek bir derin soru sorma hakkın olsa ne sorardın?",
      "Bir ilişkide kıskançlık sence sevgi göstergesi midir yoksa özgüvensizlik mi?",
      "Seninle spontane bir gece yarısı yolculuğuna çıksak nereye sürmek istersin?",
      "Bir insanda 'aura' ve çekim sence neyle oluşur?",
      "Birlikte bir şarkı dinleyecek olsak ve bu anı ölümsüzleştirse hangi şarkıyı açardın?",
      "Aşk acısı çekerken nasıl birine dönüşürsün: İçe kapanan mı, dışarı vuran mı?",
      "Sence karşı cinste en çekici giyim tarzı veya detay nedir?",
      "İlk buluşmada hesabı paylaşmak mı, bir tarafın ödemesi mi? Tavrın nedir?",
      "Beni güldürmek için nasıl bir taktik uygulardın?",
      "Bir ilişkide kendi alanına ve yalnız kalma ihtiyacına ne kadar önem verirsin?",
      "Hiç birine açılmaktan korkup duygularını içine gömdüğün oldu mu?",
      "Sence bir ilişkide heyecan ve flörtözlük yıllar geçse de korunabilir mi?",
      "Birlikte bir hafta sonu tatiline kaçacak olsak nasıl bir yer hayal edersin?",
      "Karşı tarafın hangi küçük jesti seni anında etkiler?",
      "Karakterinde aşık olunduğunda katlanılması en zor olan yanın nedir?",
      "Bir ilişkide en çok ne zaman kendini güvende ve değerli hissedersin?",
      "Sence bizim enerjimiz ve uyumumuz 10 üzerinden kaç?",
      "Bana şu an aklından geçen ama söylemeye çekindiğin tatlı bir iltifat et.",
      "Flörtleşirken mesajlaşmayı mı seversin yoksa saatlerce telefonda konuşmayı mı?",
      "Bir ilişkide sırların olmalı mıdır yoksa tam şeffaflık mı gerekir?",
      "İlk öpüşmede mekan ve anın büyüsü senin için ne kadar önemlidir?",
      "Benim hakkımda şu ana kadar öğrendiğin en ilginç veya tatlı şey ne?",
      "Seninle bir gün boyunca telefonları kapatıp baş başa kalsak günümüz nasıl geçerdi?",
      "Aşk için hayatında neleri feda edebileceğini düşünürsün?",
      "Sence zıt kutuplar mı birbirini çeker yoksa birbirine benzeyen insanlar mı?",
      "Bir ilişkide tartışmaların yapıcı olması için altın kuralın nedir?",
      "Şu an hayatında yeni bir aşka ve derin bir bağa ne kadar hazırsın?",
      "Bana sarılsan nasıl bir sarılma olurdu: Sıcak ve uzun mu, enerjik mi?",
      "En çok hangi kelimeleri sevgilinin ağzından duymak içini eritir?",
      "Gelecekteki partnerinde en çok hangi ebeveynlik ya da hayat arkadaşlığı özelliğini ararsın?",
      "Birlikte mutfağa girip yemek yapsak nasıl bir kaos veya romantizm çıkar?",
      "Bana baktığında gizemli bulduğun bir yanım var mı?",
      "Aşkın sence bir ömrü var mıdır yoksa sevgiye mi evrilir?",
      "Biriyle buluşmaya hazırlanırken en çok neye özen gösterirsin: Koku, kıyafet, saç?",
      "Bugüne kadar yaşadığın en tatlı ya da en komik flört gafı neydi?",
      "Senin için 'o doğru kişi' hissini veren en belirgin işaret nedir?",
      "Birlikte gün batımını izleyecek olsak nerede oturuyor olmak isterdin?",
      "Duygusal olarak kırılgan olduğunu karşındakine ne zaman gösterirsin?",
      "Benim ses tonum hakkında ne düşünüyorsun?",
      "İlişkide hediyeleşmek senin için ne ifade eder: Maneviyat mı, düşünülmüş olmak mı?",
      "Birbirimize vereceğimiz en güzel söz ne olabilirdi?",
      "Bu buluşmanın sonunda benden ne hatırlamak istersin?",
      "Sence bir ilişkide 'doğru zamanlama' ne kadar belirleyicidir?",
      "Birine ilk mesajı atmak mı daha zor, yoksa ilk defa 'seni seviyorum' demek mi?",
      "Bir partnerin seni en çok ne zaman 'bu insan benim için' hissettirir?",
      "Hayatında şu ana kadar kaç kez gerçek anlamda aşık oldun?",
      "Sence iyi bir ilişkinin en temel yapı taşı nedir?",
      "Karşındaki kişinin gözlerine baktığında ne tür bir şey ararsın?",
      "İlk buluşmada konuşurken en çok hangi konunun açılmasından hoşlanırsın?",
      "Şu an burada, bu anda, benden ne hissediyorsun?",
      "Bir ilişkide en çok hangi anlar seni gerçekten sarsar?",
      "Biriyle bağ kurmanın önündeki en büyük engelini ne olarak görüyorsun?",
      "Bir ilişkide sana göre 'romantizm' ne anlama gelir?",
      "Şu an yanında olmak istediğin biri var mı?",
      "Seninle ciddi olmak isteyen biri sana bunu nasıl göstermelidir?",
      "Sevginin en güzel dile geldiği an sence nedir?",
      "Bir ilişki başlamadan önce sence ne kadar süre tanışmak gerekir?",
      "Karşındaki kişiyle arandaki kimyayı en çok hangi anlarda hissedersin?",
      "Seni en çok etkileyen his: Biri tarafından görülmek mi, anlaşılmak mı, arzulanmak mı?",
      "Biri seni etkilemek istese neden yola çıkmalıdır?",
      "Şu an hayatında biri olsaydı, bu akşam ne yapardınız?",
      "Kendini en çok ne zaman sevilmeye layık hissedersin?",
      "Bir ilişkide 'kaliteli zaman' senin için ne anlama gelir?",
      "Şimdiye kadar yaptığın en cesur romantik hareket neydi?",
      "Birine yakın hissetmek için en çok neye ihtiyaç duyarsın?",
      "Aşkı anlatmak için bir renk seçsen hangisi olurdu?",
      "İlk öpücük mi, ilk 'seni seviyorum' mu — hangisi daha değerlidir?",
      "Şu an bu odada oturan birine sevgi mektubu yazsan ilk cümlen ne olurdu?",
      "Sevgi ve bağlılık arasındaki en önemli fark sence nedir?",
      "Seni ilk anda etkileyen ses tonu ve gülüş hakkında ne düşünüyorsun?",
      "Bir ilişkide 'sabırsızlıkla beklenen an' sence hangisi olmalıdır?",
      "Karşındaki biri için içinde hissettiğin ama dile getirmediğin şey nedir?",
      "Bu akşam birlikte geçirdiğimiz zamanı nasıl değerlendirirdin?"
    ]
  },

  family: {
    id: 'family',
    name: 'Aile',
    icon: '👨‍👩‍👧',
    tag: 'Sıcak & Ailevi',
    description: 'Aile üyeleri, ebeveynler ve kardeşler için derin, saygılı ve nostaljik sorular',
    theme: {
      primary: '#d97706',
      primaryDark: '#b45309',
      glow: 'rgba(217, 119, 6, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #3c1b0c 0%, #170902 100%)',
      cardBg: 'rgba(53, 23, 10, 0.85)',
      badgeBg: 'rgba(217, 119, 6, 0.15)',
      badgeBorder: 'rgba(217, 119, 6, 0.4)',
      textColor: '#ffedd5'
    },
    questions: [
      "Çocukluğumuzdan ya da geçmişimizden aklında kalan en sıcak, en mutlu aile anısı hangisi?",
      "Benimle ilgili bugüne kadar içinde biriktirdiğin ve gurur duyduğun bir başarı ya da davranış söyler misin?",
      "Ailemizde nesilden nesile aktarılmasını en çok istediğin güzel gelenek nedir?",
      "Çocukken yaptığım ve seni hem çok korkutan hem de şu an güldüren bir yaramazlığım neydi?",
      "Ailemizde değişmesini, daha modern ya da daha anlayışlı olmasını dilediğin bir kural var mı?",
      "Benim karakterimin hangi özelliğini anneye, hangisini babaya benzetiyorsun?",
      "Zor zamanlarımızda ailemizin kenetlenip atlattığı ve seni duygulandıran bir anı var mı?",
      "Büyürken sana yeterince söyleyemediğim ama hak ettiğin bir teşekkür var mı?",
      "Aile sofralarımız dendiğinde aklına gelen ilk yemek ve o masadaki kahkaha nedir?",
      "Benim geleceğimle ilgili en büyük hayalin ve temennin nedir?",
      "Geçmişe dönebilseydin aile olarak birlikte daha fazla ne yapmayı isterdin?",
      "Bende görüp 'tıpkı bana çekmiş' dediğin bir alışkanlığın ya da huyun var mı?",
      "Bana verdiğin ve hayatım boyunca bana rehberlik ettiğine inandığın en değerli hayat dersi nedir?",
      "Hiç bana hissettirmemeye çalıştığın ama ailemiz için büyük fedakarlık yaptığın bir olay oldu mu?",
      "Çocukluğumda benimle geçirdiğin en keyifli gün hangisiydi?",
      "Ailemizin en bilge ve her konuda danışılacak kişisi sence kim?",
      "Benim bir kararımı başlangıçta onaylamayıp sonradan 'iyi ki yapmış' dediğin oldu mu?",
      "Bayram sabahları ya da özel günlerdeki o eski telaşı özlüyor musun? En çok nesi aklında?",
      "Beni büyütürken en çok zorlandığın ve en çok keyif aldığın dönem hangisiydi?",
      "Birbirimize daha sık söylememiz gereken o cümle sence nedir?",
      "Kendi anne-babanla olan ilişkine kıyasla benimle olan ilişkinde neyi farklı yapmaya çalıştın?",
      "Benim hiç bilmediğim, ailenin geçmişine dair ilginç ya da komik bir aile hikayesi anlatır mısın?",
      "Bende en çok hayran olduğun ve senin sahip olmak isteyeceğin kişisel güç nedir?",
      "Ailemizde en çok kimin esprilerine gülünür ve masanın neşesi kimdir?",
      "Hakkımda endişelendiğin ama artık kendi ayaklarımın üzerinde durduğumu gördüğün konu neydi?",
      "Birlikte çıktığımız o eski tatillerden aklında kalan en canlı kare nedir?",
      "Benim sana hediye ettiğim ve sakladığın en manevi eşya hangisi?",
      "Bana kırıldığın ama 'o daha genç/çocuk' deyip içine attığın bir an oldu mu?",
      "Bizim ailemizi diğer ailelerden ayıran en belirgin ve güzel fark nedir?",
      "Gelecekte kendi kuracağım aileye bu yuvadan taşımamı istediğin en temel değer nedir?",
      "Senin gençlik yıllarında hayal ettiğin hayatla şu anki hayatın arasında en tatlı fark ne?",
      "Birlikte sustuğumuzda bile huzur bulduğumuz anları hissedebiliyor musun?",
      "Benim hakkımda başkalarına anlatırken gözlerinin parlamasına sebep olan şey nedir?",
      "Eski fotoğraf albümlerine baktığında seni en çok duygulandıran fotoğraf hangisi?",
      "Bana karşı hiç haksız yere kızdığını düşünüp sonradan vicdan azabı çektiğin oldu mu?",
      "Evimizde her zaman çalmasını istediğin o nostaljik şarkı hangisi?",
      "Benden öğrenip kendi hayatına kattığın küçük bir bakış açısı ya da yeni şey var mı?",
      "Kardeşler/aile bireyleri arasındaki dayanışmayı en güçlü hissettiğin gün neydi?",
      "Kendi çocukluğunla benim çocukluğumu kıyasladığında en çok neye imreniyorsun?",
      "Bana sarıldığında kalbinden geçen o saf duyguyu tek kelimeyle nasıl tarif edersin?",
      "Ailemizin büyüklerinden duyduğun ve kulağına küpe olan bir atasözü/nasihat var mı?",
      "Birlikte hiç denemediğimiz ama seninle baş başa yapmak istediğim bir aktivite nedir?",
      "Hangi yemeği yaptığımda ya da birlikte yediğimizde sana yuvada olduğunu hissettiriyor?",
      "Benim hangi yaş dönemime geri dönüp bana bir kez daha sarılmak isterdin?",
      "Evdeki en unutulmaz bayram ya da yılbaşı kutlamamız hangisiydi?",
      "Bana güven duyduğun en belirgin an hangisiydi?",
      "Kendi hayatında 'iyi ki bu aileyi kurmuşum' dediğin o dönüm noktası neydi?",
      "Benden gizlediğin, beni üzmemek için tek başına göğüslediğin bir zorluk oldu mu?",
      "Benimle gurur duyduğun son olayı anlatır mısın?",
      "Birbirimizi anlamakta en çok zorlandığımız kuşak farkı konusu nedir?",
      "Birlikte uzun bir araba yolculuğu yapsak nereye gitmek ve ne konuşmak isterdin?",
      "Ailemizin 'kahramanı' kimdir ve neden?",
      "Bana verebileceğin, ileride kendi çocuklarıma anlatacağım altın değerinde bir öğüt nedir?",
      "Evimizde yankılanan en komik kahkaha anını hatırlıyor musun?",
      "Senin hayatındaki en büyük fedakarlık kimin içindi?",
      "Benim hangi alışkanlığımın sana tamamen benden geçtiğini düşünüyorsun?",
      "Birlikte geçirdiğimiz zamanın değerini en çok ne zaman anladın?",
      "Bana olan sevgini kelimelere döksen bu mektubun ilk cümlesi ne olurdu?",
      "Hangi konuda bana gözün kapalı güvenirsin?",
      "Ailemizde herkesin bildiği ama kimsenin konuşmadığı tatlı bir sır var mı?",
      "Bana baktığında gelecekte beni nerede ve nasıl mutlu görüyorsun?",
      "Şu an bu masada olduğumuz için şükrettiğin en büyük sebep nedir?",
      "Seni ne kadar çok sevdiğimi ve takdir ettiğimi gerçekten hissedebiliyor musun?",
      "Ailemizin hikayesini bir roman olarak yazsak başlığı ne olurdu?",
      "Bir akrabanın senin için söylediği ve hâlâ içini ısıtan bir cümle var mı?",
      "Büyüdüğüm ev denince sana gelen ilk ses hangisi?",
      "Seninle en çok hangi konuda farklı düşünüyoruz ve bu fark bize ne öğretti?",
      "Aile olarak birlikte gülmekten kıvrandığımız son anı hatırlıyor musun?",
      "Bana söylemek istediğin ama 'zamanı değil' deyip beklediğin bir şey var mı?",
      "Benim küçüklük dönemine ait hatırladığın en sevimli anın neydi?",
      "Sence ailemizin en büyük gücü nedir?",
      "Hayatındaki en zor dönemde benden gördüğün desteği nasıl değerlendiriyorsun?",
      "Beni dışarıda birileriyle tanıştırırken nasıl tarif edersin?",
      "Birlikte oturup hiç ağlamadığımız bir film var mı, izleyelim mi?",
      "Beni bir çocukken çeken fotoğrafa baksan aklına ne gelir?",
      "Gelecekte ailemiz nasıl bir yer olmalı?",
      "Seni en iyi tanıdığımı sandığım anda yanılmış olduğumu hissettiren an neydi?",
      "Yaşlılığında seni en çok kimin bakacağını düşünüyorsun?",
      "Bizim ailemizin simgesi ya da sembolü ne olurdu?",
      "Birlikte en son ne zaman gerçekten derin bir sohbet ettik?",
      "Benden öğrenmek istediğin ama sormaktan çekindiğin bir şey var mı?",
      "Sana en çok benzeyen aile üyesi bence kimim?",
      "Ailemizde sessiz kalan ama her şeyi gören o kişi kim?",
      "Benden hiç beklediğin ama gerçekleşmemiş bir şey var mı?",
      "Seni dinlediğimi ne zaman en çok hissediyorsun?",
      "Gelecekte torunlarına bizi nasıl anlatırsın?",
      "Bana baktığında hangimizi görüyorsun — çocuğunu mu, arkadaşını mı?",
      "Evimizin en özel ve değerli köşesi sence neresidir?",
      "Şu an birlikte burada olmak nasıl bir his veriyor sana?"
    ]
  },

  dirty: {
    id: 'dirty',
    name: 'Dirty',
    icon: '🔥',
    tag: '18+ Flörtöz Gerilim',
    description: 'Flörtöz, çekici, tutkulu ve cinsel gerilimi yükselten cesur sorular',
    theme: {
      primary: '#e11d48',
      primaryDark: '#be123c',
      glow: 'rgba(225, 29, 72, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #380613 0%, #130105 100%)',
      cardBg: 'rgba(51, 6, 17, 0.85)',
      badgeBg: 'rgba(225, 29, 72, 0.15)',
      badgeBorder: 'rgba(225, 29, 72, 0.4)',
      textColor: '#ffe4e6'
    },
    questions: [
      "Karşındaki insanda seni fiziksel olarak ilk saniyede en çok çarpan detay nedir: Dudaklar, boyun, eller, gözler?",
      "Bugüne kadar yaptığın en cesur, nabız yükselten flört hamlen neydi?",
      "Bir insanda 'dayanılmaz bir çekim' hissettiğinde vücudunda oluşan ilk fiziksel tepki nedir?",
      "Sence fısıltıyla söylenen kışkırtıcı bir söz mü, yoksa uzun ve sessiz bir göz teması mı daha etkilidir?",
      "Hiç uygunsuz ya da yasak sayılabilecek bir ortamda dayanılmaz bir arzu hissettin mi?",
      "Ten uyumu senin için bir ilişkinin yüzde kaçını oluşturur?",
      "Bende en çok hangi bölgeye ya da detaya dokunmak merak uyandırıcı olurdu?",
      "Bir öpücüğün mükemmel ve unutulmaz olması için gereken en önemli kıvılcım nedir?",
      "Daha önce birine sadece kokusu yüzünden karşı konulmaz bir çekim duydun mu?",
      "Baştan çıkarma konusunda avcı mısın yoksa av olmayı mı seversin?",
      "Yatak odasında dominant ve yönlendiren taraf olmak mı hoşuna gider, teslim olmak mı?",
      "Gecenin bir yarısı gelen kışkırtıcı bir mesaj seni ne kadar kolay yoldan çıkarabilir?",
      "Giyildiğinde seni anında etkileyen kıyafet veya iç çamaşırı tarzı nedir?",
      "Seninle baş başa kalsak ve ışıklar loş olsa ilk cesur hareketin ne olurdu?",
      "Hiç aklından geçen ama sesli söylemeye utandığın erotik bir hayalin oldu mu?",
      "Boyundan öpülmek mi, belden kavranmak mı senin nefesini daha çok keser?",
      "Bir buluşmada cinsel gerilimi bilerek tırmandırmayı sever misin?",
      "Karşındaki kişinin seni arzuladığını belirten en net beden dili hareketi sence nedir?",
      "Hiç kimsenin bilmediği gizli bir erojen bölgen var mı?",
      "Senin için 'seksi' kelimesinin tam karşılığı olan davranış nedir?",
      "Dudak ısırmak, saçla oynamak ya da gözleri kısmak... Hangi hareket seni savunmasız bırakır?",
      "Spontane, tutkulu ve hızlı bir an mı yoksa saatlerce süren yavaş ve derin bir temas mı?",
      "Beni şu an baştan çıkarmak için 3 cümlen olsa ne söylerdin?",
      "Hiç rüyanda tanıdığın biriyle tutkulu bir kaçamak yaşayıp uyanınca garip hissettin mi?",
      "Sence bir öpüşme ne kadar süre sonra ciddileşip kontrolden çıkmalıdır?",
      "Araba içi, asansör, balkon... Sıra dışı mekanlarda flört gerilimi yaşamak sana heyecan verir mi?",
      "Karşı tarafın kulağına fısıldamak istediğin en cesur şey ne olurdu?",
      "Dokunulmaktan en çok zevk aldığın hassas bölgen neresidir?",
      "Bir ilişkide tutkunun hiç sönmemesi için en gizli taktiğin nedir?",
      "Sence cinsel çekim sonradan kazanılabilir mi yoksa ilk anda var mıdır ya da hiç yoktur?",
      "Gözlerin bağlıyken sadece dokunuşlarla ve sesle yönlendirilmek ilgini çeker mi?",
      "Bana baktığında şu an içinde uyanan en cesur düşünce nedir?",
      "Hiç birine karşı koymak isteyip de çekimine yenik düştüğün oldu mu?",
      "Masaj yapmayı mı daha çok seversin, masajla şımartılmayı mı?",
      "Partnerinin üzerinde kontrol sahibi olmak mı, yoksa ipleri tamamen bırakmak mı?",
      "Sence afrodizyak etkisi yaratan en güçlü şey nedir: Müzik, koku, içki, sözler?",
      "Bir kadında/erkekte en çekici bulduğun dekolte veya vücut hattı neresidir?",
      "Hiç tehlikeli bir yerde yakalanma korkusuyla flörtleştin mi?",
      "Sence tutkulu bir sarılmada eller tam olarak nereye gitmelidir?",
      "Seni bir bakışıyla baştan çıkarabilecek birine 'hayır' deme olasılığın nedir?",
      "Gece boyunca sürecek bir oyun oynasak ilk cezan ne olurdu?",
      "Fiziksel temas olmadan sadece konuşarak tahrik olmak mümkün müdür?",
      "En çok hangi kelimelerin fısıldanması kalbinin ritmini hızlandırır?",
      "Bana şu an dokunma şansın olsa ilk nereye dokunurdun?",
      "İç çamaşırı seçiminde rahatlık mı ön plandadır, yoksa baştan çıkarıcılık mı?",
      "Sence aşk mı seksi güzelleştirir yoksa iyi seks mi aşkı doğurur?",
      "Hiç tanımadığın biriyle göz göze gelip saf bir cinsel elektrik hissettiğin oldu mu?",
      "Birlikte bir duş ya da jakuzi keyfi hayal etsen ambiyans nasıl olurdu?",
      "Senin için 'baştan çıkarmanın ustası' olmanın altın kuralı nedir?",
      "Gözlerimin içine 10 saniye boyunca kırpmadan bakabilir misin?",
      "Partnerinin seni kucağına alması ya da duvara yaslaması seni heyecanlandırır mı?",
      "Sence en seksi dans türü hangisidir?",
      "Kendini en çekici ve karşı konulmaz hissettiğin anlar hangileridir?",
      "Sabah uyanır uyanmaz tutkulu bir temas mı, gece geç saatlerin yorgun sevişmesi mi?",
      "Beni tek bir kelimeyle 'çekici' kılan özelliğim nedir?",
      "Hiç biriyle sadece fiziksel çekim yüzünden günlerce aklından çıkaramadığın oldu mu?",
      "Rol yapma veya kurgusal senaryolar ilgini çeker mi?",
      "Partnerinin teninden parfüm kokusu mu gelmeli, yoksa doğal ten kokusu mu?",
      "Dudaklarıma baktığında aklından geçen ilk düşünce ne?",
      "Gecenin sonunda 'keşke daha ileri gitseydik' dediğin bir anın oldu mu?",
      "Seni baştan çıkarmak isteyen birinin asla yapmaması gereken hata nedir?",
      "Şu an üzerimdeki kıyafetlerden birini çıkarma hakkın olsa hangisini seçerdin?",
      "Birlikte bu odadan çıksak ilk nereye gitmek isterdin?",
      "Birine arzuladığını fısıldamak için doğru zaman ne zaman gelir?",
      "Karşındaki kişinin saçını okşarken ya da boynunu tutarken ne hissedersin?",
      "Seninle yakınlaşmak isteyen biri önce hangi sinyali vermelidir?",
      "Bir ilişkide seni en çok heyecanlandıran 'ilk kez' anı hangisidir?",
      "Biriyle yalnız kaldığında ortamın havasını değiştiren şey nedir?",
      "Gecenin ortasında gözün açıldığında yanında biri olmasını mı yoksa özgür alanı mı tercih edersin?",
      "Sence en uzun süren öpücük kaç dakika olmalıdır?",
      "Bir partnerinin seni en beklenmedik anda sarması ne kadar etkiler?",
      "Şu an en çok hangi dokunuşa ihtiyaç duyuyorsun?",
      "Birine ilk kez dokunduğunda en çok neye dikkat edersin?",
      "Seni 'bu gece senden gözümü alamıyorum' dedirten detay nedir?",
      "Yakınlık kurarken sessizlik mi yoksa konuşmak mı daha anlamlıdır?",
      "Bir partner senin için nasıl bir gerginliği 'iyi bir gerginliğe' dönüştürür?",
      "Seninle başbaşa kalan biri hangi hissi en fazla alır: Güven, heyecan, sıcaklık?",
      "Şu an bu odada seni en çok cezbeden şey nedir?",
      "Bir öpücüğü 'hafıza kaydeden' kılan nedir?",
      "Beni en çok şaşırtabilecek davranışın ne olurdu?",
      "İlk buluşmada dokunmanın doğal hissettirdiği an ne zaman gelir?",
      "Kendinden geçirten bir anın tam öncesinde neler hissediyorsun?",
      "Seninle dans etsem hangi müziği çalardın ve nasıl tutardın beni?",
      "Şu an bana bakışlarınla ne söylemek istiyorsun?",
      "Bir ilişkide bedensel yakınlık ile duygusal yakınlık senin için hangisi önce gelir?",
      "Seni ilk öptüğümde ne hissettiğini merak ediyorum, gerçekten söyler misin?",
      "Şu an bu anı nasıl daha unutulmaz kılabiliriz?"
    ]
  },

  nsfw: {
    id: 'nsfw',
    name: 'NSFW',
    icon: '🔞',
    tag: '18+ Sansürsüz & Açık',
    description: 'Doğrudan, sansürsüz, yetişkin fantezileri ve cinsel deneyimler',
    theme: {
      primary: '#dc2626',
      primaryDark: '#991b1b',
      glow: 'rgba(220, 38, 38, 0.45)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #1a0305 0%, #050102 100%)',
      cardBg: 'rgba(20, 3, 5, 0.92)',
      badgeBg: 'rgba(220, 38, 38, 0.2)',
      badgeBorder: 'rgba(220, 38, 38, 0.5)',
      textColor: '#fee2e2'
    },
    questions: [
      "Yatakta en çok zevk aldığın ve olmazsa olmazın olan pozisyon hangisidir?",
      "Bugüne kadar yaşadığın en unutulmaz, en yoğun orgazm deneyimin nasıldı?",
      "Hiç kimseye anlatmadığın ama gizliden gizliye denemek istediğin en uç fantezin nedir?",
      "Dirty talk seni ne kadar tahrik eder ve hangi kelimeler favorindir?",
      "Oral seks senin için bir ön sevişme detayı mıdır yoksa ana yemek kadar değerli mi?",
      "BDSM, hafif bağlama, kelepçe ya da göz bandı gibi fantezilere ilgin var mı?",
      "Bugüne kadar seks yaptığın en sıra dışı, riskli ya da tehlikeli mekan neresiydi?",
      "Hiç üçlü ya da grup fantezisi düşündün mü ya da deneyimledin mi?",
      "Seks sırasında canının hafifçe yanmasından zevk alır mısın?",
      "Bir partnerde seni saniyeler içinde tamamen seksten soğutan şey nedir?",
      "Sekste kontrolün tamamen sende olması mı, yoksa karşı tarafın seni tamamen yönetmesi mi?",
      "Yetişkin içerik izleme sıklığın nedir ve en çok hangi kategoriler ilgini çeker?",
      "Seks oyuncakları kullanma konusunda deneyimin ve fikrin nedir?",
      "Hiç kamuya açık bir alanda seks yaptın mı?",
      "Senin için ideal bir sevişmenin süresi ne kadar olmalıdır: Hızlı ve sert mi, uzun ve maraton mu?",
      "Hiç sexting yaparken orgazm oldun mu ya da kamera karşısında soyundun mu?",
      "Fetişlerin var mı: Ayak, çorap, deri, üniforma gibi detaylar seni tahrik eder mi?",
      "Partnerinin vücudunda yalamaktan veya öpmekten en çok doyamadığın yer neresidir?",
      "Hiç birden fazla kez art arda orgazm yaşadın mı?",
      "Yatakta en çok ses çıkaran, inleyen taraf mısın yoksa sessizce yaşayanlardan mı?",
      "Günün hangi saatinde seks yapmak sana en yüksek hazzı verir: Sabah mı, gece yarısı mı?",
      "Hiç sadece fiziksel doyum için arkadaşça seks yaşadın mı?",
      "Sekste sınırların nelerdir; asla yapmam dediğin şey nedir?",
      "Ayna karşısında seks yapmak veya sevişirken kendinizi izlemek seni tahrik eder mi?",
      "Hiç partnerinle birlikte video/fotoğraf çekip sakladığın oldu mu?",
      "Yatakta karşı taraftan duyduğun ve seni anında tepe noktaya ulaştıran en cesur cümle neydi?",
      "Ön sevişme senin için ne kadar sürmeli ve en çok hangi dokunuşlar seni hazırlar?",
      "Hiç tanımadığın biriyle bir gecelik ilişki yaşadın mı, nasıldı?",
      "Mastürbasyon yaparken en çok neyi veya kimi hayal edersin?",
      "Vücuduna çikolata, krem şanti veya masaj yağı sürülerek sevişmek ister miydin?",
      "Partnerinin seni yönlendirip ne yapacağını emretmesi sana nasıl hissettirir?",
      "Hiç cinsel ilişki sırasında komik ya da utanç verici bir kaza yaşadın mı?",
      "Seks sırasında göz teması kurmak mı daha yoğun hissettirir yoksa gözlerin kapalı olması mı?",
      "Daha önce anal deneyim yaşadın mı, bu konudaki merakın ve sınırın nedir?",
      "Yatakta ne kadar maceracısın: 1-10 arası puan versen kaç olurdun?",
      "Partnerinin seni aniden soyup beklemediğin bir anda başlatması seni ne kadar etkiler?",
      "Hiç sarhoşken yaşanan ve sabah hatırladığında seni şaşırtan bir seks anın oldu mu?",
      "Sekste en çok hangi duyu organın seni zirveye taşır: Dokunma, tat, koku, işitme?",
      "Yatak odasında kostüm ya da rol yapma denedin mi?",
      "Hiç birine karşı sadece cinsel takıntı boyutunda yoğun bir arzu duydun mu?",
      "Seks sonrası en çok ne yapmayı seversin: Sarılıp uyumak, duş, sohbet?",
      "Karşı tarafın zevk alması mı seni daha çok tatmin eder, kendi zevkin mi?",
      "Seks sırasında konuşulmasından hoşlandığın en cüretkar konu nedir?",
      "Partnerinin seni izlerken mastürbasyon yapması seni tahrik eder mi?",
      "Hiç evde başkaları varken sessizce sevişmek zorunda kaldın mı?",
      "Senin için 'en vahşi' seks deneyimin hangi mekanda gerçekleşti?",
      "Yatakta reddedilmekten korktuğun için söyleyemediğin bir istek var mı?",
      "Seks yaparken müzik çalması şart mıdır yoksa nefes ve ten sesleri yeterli mi?",
      "Karşındaki kişinin sana özel bir dans yapmasını ister miydin?",
      "Hiç aynı gün içinde 3 veya daha fazla kez seviştiğin oldu mu?",
      "Sekste en çok 'keşke daha önce deneseydim' dediğin şey ne oldu?",
      "Vücudunda partnerinin dokunmasıyla anında titremene sebep olan nokta neresi?",
      "Hiç bir fantezini gerçekleştirdikten sonra hayal kırıklığına uğradığın oldu mu?",
      "Sence mükemmel bir seksin sırrı teknik midir, tutku mu, yoksa duygusal bağ mı?",
      "Hiç otel odasında ya da tatilde tüm günü yataktan çıkmadan geçirdiğin oldu mu?",
      "Sekste en cömert olduğun ve partnerini mest ettiğin özelliğin nedir?",
      "Yatakta tabuların yıkılması senin için ne kadar kolaydır?",
      "Hiç seksten hemen sonra yeniden aşırı arzulandığın bir partnerin oldu mu?",
      "Şu an tam burada, sınırsız ve kuralsız olsaydık aklındaki ilk hamle ne olurdu?",
      "Bir partnerini yatakta en çok şaşırtmak için ne yapardın?",
      "Sekste 'yasak' hissettiren ama tam o yüzden daha çekici gelen bir şey var mı?",
      "Birileri sizi duyabilecekken sessiz kalmak mı daha zor, yoksa tamamen serbest olmak mı?",
      "Hiç birine karşı koyamayıp çok kısa tanıştıktan sonra birlikte olduğun oldu mu?",
      "En uzun ön sevişmen ne kadar sürdü?",
      "Bir partnerinde seksüel olarak en çok ne zaman güçlü çekim hissedersin?",
      "Sekste en çok hangi duyguyu yaşıyorsun: Güç, teslim, haz, bağlılık?",
      "Hiç fantezinde olmayan biriyle seks yaşayıp şaşırdığın oldu mu?",
      "Partnerinin fiziksel olarak hangi özelliği seni en çok büyüler?",
      "Sekste 'mükemmel an' sence nasıl başlar?",
      "Seksüel bir deneyi reddettiğin ve sonradan pişman olduğun bir şey var mı?",
      "Yatak performansın hakkında en çok hangi geri bildirimi aldın?",
      "Sabahın köründe uyandırılarak başlayan bir seks deneyimin oldu mu?",
      "Hiç pornografide gördüğün bir sahneyi gerçek hayatta denemek istediğin oldu mu?",
      "Seksüel açıdan en özgür hissettiğin an hangisiydi?",
      "Birine 'bu gece beni çıldırtacaksın' hissini veren davranış nedir?",
      "Sevişirken müzik açsan hangi tür müzik seçerdin?",
      "Hiç tamamen karanlıkta seks yaşadın mı, nasıldı?",
      "Partner değiştirmenin ilk gecesi seni en çok ne düşündürür?",
      "Seksüel bir sınırı aşıp 'aslında iyiymiş' dediğin oldu mu?",
      "Bedeninizde birbirini en çok uyandıran yer neresidir?",
      "Bir ilişkide seksüel uyum mu yoksa duygusal bağ mı önce kurulur?",
      "Şu an yanında olmak istediğin ve düşünceni en çok meşgul eden kişi kim?",
      "Seksüel hayatında en büyük 'cesaret' yaptığın an neydi?",
      "Bugüne kadar seks konusunda verdiğin en iyi karar ne oldu?",
      "Şu an bu ortamda kim seni en çok heyecanlandırıyor?"
    ]
  },

  deep: {
    id: 'deep',
    name: 'En Gizli Sırlar',
    icon: '🤫',
    tag: 'İtiraflar & Mahremiyet',
    description: 'Maskeleri düşüren, en derin itirafları ve gizli gerçekleri ortaya çıkaran sorular',
    theme: {
      primary: '#8b5cf6',
      primaryDark: '#7c3aed',
      glow: 'rgba(139, 92, 246, 0.35)',
      bgGradient: 'radial-gradient(circle at 50% 20%, #1e1035 0%, #0c0517 100%)',
      cardBg: 'rgba(28, 14, 51, 0.88)',
      badgeBg: 'rgba(139, 92, 246, 0.15)',
      badgeBorder: 'rgba(139, 92, 246, 0.4)',
      textColor: '#ede9fe'
    },
    questions: [
      "Hayatın boyunca söylediğin ve ortaya çıkarsa herkesi şok edecek en büyük yalan neydi?",
      "En yakın arkadaşının dahi bilmediği, mezara kadar götürmeyi düşündüğün sırrın nedir?",
      "Sosyal medyada gizlice sahte hesapla stalk'ladığın kişi kim ve en son ne zaman baktın?",
      "Hiç bir arkadaşının sevgilisine ya da eski sevgilisine karşı bir anlık da olsa ilgi duydun mu?",
      "Yaptığın ve hâlâ düşündükçe vicdan azabı çektiğin en bencilce hareketin neydi?",
      "Grup içinde ya da arkadaş çevrende içten içe en çok kıskandığın veya çekemediğin kişi kim?",
      "İnsanlara gösterdiğin mutlu/güçlü maskenin arkasında en çok sakladığın zayıflığın nedir?",
      "Hiç birinin arkasından çok ağır konuşup yüzüne karşı hiçbir şey olmamış gibi güldün mü?",
      "Hayatında birine yaptığın en büyük haksızlık ya da kötülük neydi?",
      "Telefonun şu an herkesin eline geçse ve şifresi açılsa silmek için ilk koşacağın şey ne olurdu?",
      "Hiç bir arkadaşının başarısına üzüldüğün ya da başarısızlığına gizlice sevindiğin oldu mu?",
      "Ailenden ya da sevdiklerinden gizlediğin en büyük harcaman veya maddi kaybın neydi?",
      "Kendinle ilgili en çok utandığın fiziksel ya da karakteristik kusurun nedir?",
      "Hiç bir ilişkide partnerini aldattın mı (duygusal ya da fiziksel)?",
      "Bugüne kadar birine söylediğin en acımasız ve kalbini kıran söz neydi?",
      "Hiç bir ortamdan kaçmak veya birinden kurtulmak için uydurduğun en büyük yalan neydi?",
      "Şu anki hayatında kimsenin bilmediği gizli bir bağımlılığın ya da takıntın var mı?",
      "Hiç başkasının sana emanet ettiği çok gizli bir sırrı üçüncü bir kişiye anlattın mı?",
      "Biri hakkında 'asla öğrenmemeli' dediğin çok kötü bir düşüncen oldu mu?",
      "Hiç marketten, iş yerinden ya da bir arkadaştan izinsiz bir şey aşırdın mı?",
      "Geçmişinde yasal olarak sınırlarda gezindiğin ya da suç sayılabilecek bir olay var mı?",
      "En son ne zaman tek başına odanda hıçkırarak ağladın ve sebebi neydi?",
      "İçinde biriktirdiğin ve yüzüne haykırmak istediğin ama korktuğun kişi kim?",
      "Hiç birinin ilişkisini bozmaya çalıştığın ya da aralarını açacak bir dedikodu yaydığın oldu mu?",
      "Kendinde en çok nefret ettiğin ama değiştiremediğin toksik özelliğin nedir?",
      "Bugüne kadar yaşadığın en aşağılayıcı ya da küçük düşürücü an neydi?",
      "Hiç birine aşık olmadığı halde sırf yalnız kalmamak ya da çıkar için birlikte oldun mu?",
      "Sosyal medyada paylaştığın en sahte, sadece gösteriş amaçlı olan gönderin hangisiydi?",
      "Ailenden tamamen gizlediğin ve asla bilmelerini istemediğin bir ilişkin ya da dostluğun oldu mu?",
      "Hiç intikam almak için plan yapıp birine sinsice zarar verdin mi?",
      "Şu an hayatından tek bir tuşla tamamen silebileceğin 3 kişi kim olurdu?",
      "Hiç birinin özel mesajlarını, günlüğünü ya da telefonunu gizlice karıştırdın mı?",
      "Kendini zeki, yetenekli ya da başarılı göstermek için uydurduğun büyük bir abartı var mı?",
      "En son ne zaman birine 'seni seviyorum' deyip aslında hiçbir şey hissetmedin?",
      "Gizli gizli dinlediğin ve arkadaşlarının bilse seninle dalga geçeceği müzik türü kim?",
      "Hiç borç alıp bilerek geri ödemediğin ya da unutturmaya çalıştığın biri oldu mu?",
      "Hayatındaki en büyük pişmanlığın olan o tek karar nedir?",
      "Hiç bir kaza yapıp başkasının üzerine attın mı?",
      "İnsanların senin hakkındaki en büyük yanılgısı nedir ve bunu düzeltmeye neden çalışmıyorsun?",
      "Gruptaki kişilerden birinin arkasından en son ne zaman dedikodu yaptın?",
      "Hiç sahte gözyaşı dökerek bir durumu kendi lehine çevirdin mi?",
      "Kendini en çok ne zaman çaresiz, yetersiz ve başarısız hissettin?",
      "Geçmişte sana aşık olan birinin duygularıyla bilerek ve isteyerek oynadın mı?",
      "Hiçbir zaman affetmeyeceğin ve içten içe intikam soğukluğunu koruduğun biri var mı?",
      "Gece yatağa yattığında uykunu kaçıran en karanlık düşüncen nedir?",
      "Hiçbir çıkarın olmadığı halde durduk yere söylediğin anlamsız bir yalan oldu mu?",
      "En son ne zaman birine verdiğin sözü bilerek çiğnedin?",
      "Kendi ailenle ilgili dışarıya asla yansıtmadığın en büyük problem nedir?",
      "Hiç bir arkadaşının kıyafetini, tarzını ya da hayatını içten içe rezil bulduğun oldu mu?",
      "Kendini şu an bu masadaki herkesten üstün gördüğün tek bir konu söyle.",
      "Hiçbir zaman gerçekleşmeyeceğini bildiğin ama vazgeçemediğin gizli hayalin ne?",
      "Sosyal statü veya popülerlik kazanmak için arkadaş grubunu sattığın oldu mu?",
      "Hiç birini stalk'larken yanlışlıkla fotoğrafını beğenip panikle hesabı dondurdun mu?",
      "Başkalarının acısına ya da düşüşüne içten içe 'oh olsun' dediğin bir an oldu mu?",
      "İçinde sakladığın ve bir gün ortaya çıkarsa itibarını zedeleyecek şey nedir?",
      "Hiç partnerinin hediye ettiği bir şeyi çöpe attın ya da başkasına verdin mi?",
      "Kendine bile itiraf etmekte zorlandığın en karanlık arzun nedir?",
      "En son ne zaman birine yardım edebilecekken sırf üşendiğin için görmezden geldin?",
      "Geçmişte yaptığın ve şu anki aklınla asla yanından bile geçmeyeceğin aptallık neydi?",
      "Biriyle sadece parası, arabası ya da mekanı için görüştüğün oldu mu?",
      "Hayatında kaç kez gerçekten aşık oldun ve şu an kimi unutamadın?",
      "İnsanların yanında asla yapmadığın ama yalnızken yaptığın en garip alışkanlığın ne?",
      "Hiç birini kıskandırmak için yapmacık bir mutluluk tiyatrosu oynadın mı?",
      "Eğer bugün dünyanın son günü olsaydı itiraf edeceğin o son cümle ne olurdu?",
      "Bu masadaki birine şu an bakıp içinde tuttuğun en dürüst gerçeği söyler misin?",
      "Hiç kendin hakkında internette bir şey aramak zorunda kaldın mı?",
      "Şu an hayatında en çok ne seni mahkum ediyor ama kimseye söyleyemiyorsun?",
      "Seni en derinden tanıyan insan ne bilir ki başkaları bilmiyor?",
      "Hayatında yapmak isteyip de vicdanın izin vermediği şey nedir?",
      "En son ne zaman kendinle dürüst bir hesaplaşma yaptın?",
      "Gizlice takip ettiğin ama hiç etkileşime girmediğin bir hesap var mı?",
      "Kendi kendinle en barışık olduğun an hangi andır?",
      "Şu an hayatında 'evet' demen gereken ama 'hayır' dediğin bir şey nedir?",
      "İnsanlar seni tanıyor zannetse de bilmediği tek şey nedir?",
      "Kendinle ilgili en büyük yanılsamanı fark ettiğin an neydi?",
      "Hiç birini sevdiğini sanıp sonradan bunun sadece yalnızlık olduğunu anladın mı?",
      "Şu an en çok neyi inkar etmek istiyorsun?",
      "Kendi karakterinin en utandığın yanını içtenlikle itiraf edebilir misin?",
      "Şimdiye kadar en uzun süre yaşattığın sır ne kadar süredir saklıyor?",
      "Hayatında geriye dönüp 'bu beni çok değiştirdi' dediğin ama kimseye anlatamadığın olay nedir?",
      "Şu an bu odada seni en iyi anlayan kişi kim ve sen bunu ona söyledin mi?",
      "En son ne zaman 'bu kadar' deyip durman gerektiğini hissettin ama duramadın?",
      "Gece yarısı düşündüğünde kalbini en çok sıkan şey nedir?",
      "Şu an herkese söylemek istediğin ama cesaretini bulamadığın cümle nedir?",
      "Kendinle ilgili en korktuğun ve gerçek olabileceğini düşündüğün şey nedir?",
      "Şimdiye kadar yaptığın en iyi şey ne — ama bunu neden kimseye söylemiyorsun?",
      "Bu masada oturan insanların bilmesini en çok isteyip de söyleyemediğin şey ne?"
    ]
  }
};

if (typeof window !== 'undefined') {
  window.GAME_CATEGORIES = CATEGORIES;
}
